# Generated by Django 4.0.5 on 2022-06-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_employee_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='middlename',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=50),
        ),
    ]
