# Generated by Django 4.0.5 on 2022-06-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='middlename',
            field=models.CharField(max_length=10),
        ),
    ]
